-- MySQL Script generated by MySQL Workbench
-- Fri Jul 26 22:11:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `google_id` VARCHAR(95) NULL,
  `nombre` VARCHAR(35) NOT NULL,
  `apellidos` VARCHAR(45) NULL,
  `correo_electronico` VARCHAR(65) NOT NULL,
  `contraseña` VARCHAR(35) NULL,
  `telefono` VARCHAR(15) NULL,
  `foto` BLOB NULL,
  `genero` VARCHAR(10) NULL,
  `tipoUsuario` VARCHAR(15) NULL,
  `sobreMi` VARCHAR(300) NULL DEFAULT 'Comprometido con la protección y el cuidado de todos los seres animales.',
  `ubicacion` VARCHAR(150) NULL,
  `token` VARCHAR(8) NULL,
  `confirmado` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Ubicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ubicacion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Ubicacion` (
  `idUbicacion` INT NOT NULL AUTO_INCREMENT,
  `latitud` DECIMAL(30,20) NOT NULL,
  `longitud` DECIMAL(30,20) NOT NULL,
  PRIMARY KEY (`idUbicacion`))
ENGINE = InnoDB
COMMENT = '	';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Animal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Animal` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Animal` (
  `idAnimal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `sexo` VARCHAR(10) NOT NULL,
  `tipoAnimal` VARCHAR(25) NOT NULL,
  `raza` VARCHAR(30) NOT NULL,
  `estadoSalud` VARCHAR(25) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `tamanio` VARCHAR(20) NOT NULL,
  `peso` VARCHAR(10) NOT NULL,
  `edad` VARCHAR(15) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `imagen` BLOB NOT NULL,
  `fechaReporte` DATE NOT NULL,
  `idUsuario` INT NOT NULL,
  `idUbicacion` INT NOT NULL,
  PRIMARY KEY (`idAnimal`),
  INDEX `idUsuario_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `idUbicacion_idx` (`idUbicacion` ASC) VISIBLE,
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idUbicacion`
    FOREIGN KEY (`idUbicacion`)
    REFERENCES `Ubicacion` (`idUbicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Tip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tip` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Tip` (
  `idTip` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(30) NOT NULL,
  `descripcion` VARCHAR(550) NOT NULL,
  `imagen` BLOB NOT NULL,
  PRIMARY KEY (`idTip`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Organizacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Organizacion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Organizacion` (
  `idOrganizacion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(15) NOT NULL,
  `correo` VARCHAR(65) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(1550) NOT NULL,
  `imagen` BLOB NOT NULL,
  PRIMARY KEY (`idOrganizacion`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Blog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Blog` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Blog` (
  `idBlog` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `subtitulo` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(4500) NOT NULL,
  `imagen` BLOB NOT NULL,
  PRIMARY KEY (`idBlog`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
